name: first CI
on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited]
jobs:
  greet:
    env:
      MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: List all files
        run: ls -l 
      - uses: actions/checkout@v5 
      - run: ls -l
      - name: run multiple Scripts
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"